config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/order-products/:period_id/:user_id', to: 'reports#order_products', as: 'order_products'

  post 'reports/send-order-products/:period_id/:user_id', to: 'reports#send_order_products', as: 'send_products'
  get 'reports/success/:spreadsheet_id', to: 'reports#success', as: 'report_success'
  resources :periods do
    get '/for-cook/:user_id', to: 'orders#for_cook', as: 'for_cook'
    resources :orders
    resources :remainders
    resources :purchases
  end

  resources :places
  resources :products

  resources :dishes do
    resources :ingredients
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/period.rb
class Period < ApplicationRecord
  include ValidatorPeriods
  has_many :order
  has_many :purchases
  has_many :remainders

  validates :days, presence: true, numericality: true
  validates_presence_of :start_date, :finish_date

  validates_with OrderPeriodDate
  validates_with MaximumFinishDate

  scope :period_before, -> (id) { where('id < ?', id.to_i).order(id: :desc).limit(1).first }

  def name
    "#{start_date.strftime("%d/%m/%Y")} - #{finish_date.strftime("%d/%m/%Y")}"
  end

end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  load_and_authorize_resource
  include DateForPeriods

  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  def index
    @periods = Period.all.order(finish_date: :desc).page(params[:page]).per(10)
  end

  # GET /periods/1
  def show
  end

  # GET /periods/new
  def new
    @period = default_period
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  def create
    @period = Period.new(period_params)

    if @period.save
      redirect_to periods_path, notice: t('periods.msg.success.create')
    else
      render :new
    end
  end

  # PATCH/PUT /periods/1
  def update
    if @period.update(period_params)
      redirect_to @period, notice: t('periods.msg.success.update')
    else
      render :edit
    end
  end

  # DELETE /periods/1
  def destroy
    @period.destroy
    redirect_to periods_url, notice: t('periods.msg.success.destroy')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:start_date, :finish_date, :days)
    end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_with(model: period, local: true) do |form| %>

  <% if period.errors.any? %>
      <% period.errors.full_messages.each do |error| %>
          <%= alert_generator(error) %>
      <% end %>
  <% end %>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label t('periods.tab.start_day') %>
          <%= form.date_select :start_date, id: :period_start_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label t('periods.tab.finish_day') %>
          <%= form.date_select :finish_date, id: :period_finish_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label t('periods.tab.days') %>
          <%= form.number_field :days, id: :period_days, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit t('periods.save'), class: 'btn btn-primary btn-block' %>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
<% end %>

app/views/periods/edit.html.erb
<div class="container">
  <%= provide(:title, t('periods.name')) %>
  <h1><%= t('periods.view.title_edit') %></h1>

  <%= render 'form', period: @period %>
</div>


<div class="container btn-container">
  <%= render 'shared/link_default', { path: periods_path, title: t('button.back') } %>
  <%= render 'shared/link_default', { path: @period, title: t('button.show') } %>
</div>

app/views/periods/index.html.erb
<div class="container empty-container">
  <%= provide(:title, t('periods.name')) %>
  <%= paginate @periods %>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('periods.name') %></th>
        <th><%= t('periods.tab.days') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @periods.each do |period| %>
        <tr>
          <td><%= period.name %></td>
          <td><%= period.days %></td>
          <td>
            <%= link_to t('periods.view.link_orders'), period_orders_path(period) %>
          </td>

          <td>
            <%= link_to t('purchases.name'), period_purchases_path(period) %>
          </td>
          <td>
            <%= link_to t('remainders.name'), period_remainders_path(period) %>
          </td>
          <td>
            <% if can?(:update, period) %>
                <%= link_to edit_period_path(period) do %>
                    <i class="fa fa-pencil-square-o"></i>
                <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @periods %>
</div>

<div class="container btn-container">
  <% if can?(:create, Period) %>
    <%= render 'shared/link_default', { path: new_period_path, title: t('periods.view.title_new') } %>
  <% end %>
</div>

app/views/periods/new.html.erb
<div class="container">
  <%= provide(:title, t('periods.name')) %>
  <h1><%= t('periods.view.title_new') %></h1>

  <%= render 'form', period: @period %>

</div>

<div class="container btn-container">
  <%= render 'shared/link_default', { path: periods_path, title: t('button.back') } %>
</div>

app/views/periods/show.html.erb
<div class="container">
  <%= provide(:title, t('periods.name')) %>
  <h1><%= t('periods.view.title_show') %></h1>
  <p>
    <strong>Start date:</strong>
    <%= @period.start_date %>
  </p>

  <p>
    <strong>Finish date:</strong>
    <%= @period.finish_date %>
  </p>

  <p>
    <strong>Days:</strong>
    <%= @period.days %>
  </p>
</div>

<div class="container btn-container">
  <% if can?(:update, @period) %>
    <%= render 'shared/link_default', { path: edit_period_path(@period), title: t('button.edit') } %>
  <% end %>
  <%= render 'shared/link_default', { path: periods_path, title: t('button.back') } %>
</div>