config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/order-products/:period_id/:user_id', to: 'reports#order_products', as: 'order_products'

  post 'reports/send-order-products/:period_id/:user_id', to: 'reports#send_order_products', as: 'send_products'
  get 'reports/success/:spreadsheet_id', to: 'reports#success', as: 'report_success'
  resources :periods do
    get '/for-cook/:user_id', to: 'orders#for_cook', as: 'for_cook'
    resources :orders
    resources :remainders
    resources :purchases
  end

  resources :places
  resources :products

  resources :dishes do
    resources :ingredients
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner-slider">
  <div class="container">
    <div class="slider">
      <div class="callbacks_container">
        <ul class="rslides" id="slider4">
          <li>
            <div class="banner-info">
              <h3><%= t('banner.slider.title1') %></h3>
              <p><%= t('banner.slider.text1') %></p>
              <%= link_to t('dishes.name'), dishes_path %>
            </div>
          </li>
          <li>
            <div class="banner-info">
              <h3><%= t('banner.slider.title2') %></h3>
              <p><%= t('banner.slider.text2') %></p>
              <%= link_to t('dishes.name'), dishes_path %>
            </div>
          </li>
          <li>
            <div class="banner-info">
              <h3><%= t('banner.slider.title3') %></h3>
              <p><%= t('banner.slider.text3') %></p>
              <%= link_to t('dishes.name'), dishes_path %>
            </div>
          </li>
          <li>
            <div class="banner-info">
              <h3><%= t('banner.slider.title4') %></h3>
              <p><%= t('banner.slider.text4') %></p>
              <%= link_to t('dishes.name'), dishes_path %>
            </div>
          </li>
          <li>
            <div class="banner-info">
              <h3><%= t('banner.slider.title5') %></h3>
              <p><%= t('banner.slider.text5') %></p>
              <%= link_to t('dishes.name'), dishes_path %>
            </div>
          </li>
        </ul>
      </div>
      <script>
        // You can also use "$(window).load(function() {"
        $(function () {
          // Slideshow 4
          $("#slider4").responsiveSlides({
            auto: true,
            pager:true,
            nav:false,
            speed: 1000,
            namespace: "callbacks",
            before: function () {
              $('.events').append("<li>before event fired.</li>");
            },
            after: function () {
              $('.events').append("<li>after event fired.</li>");
            }
          });

        });
      </script>
      <!--banner Slider starts Here-->
    </div>
  </div>
</div>

app/views/shared/_footter_application.html.erb
<div class="agileits-copyright">
  <div class="container">
    <p>© 2017 Kmet. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
  </div>
</div>

app/views/shared/_link_default.html.erb
<%= link_to path, class: 'link-btn' do %>
    <span class="btn btn-default"><%= title %></span>
<% end %>

app/views/shared/_nav_application.html.erb
  <!--header-->
  <div class="header">
    <div class="logo">
      <h1>
        <%= link_to root_path do %>
            <%= image_tag 'fransua_logo.jpg', width: '100' %>
        <% end %>
      </h1>
    </div>
    <div class="top-nav">
      <span class="menu"><%= image_tag 'menu.png' %></span>
      <ul>

        <li><%= link_to t('home'), root_path, class: "#{check_active(root_path)}" %></li>

        <li><%= link_to t('dishes.name'), dishes_path, class: "#{check_active(dishes_path)}" %></li>

        <% if can?(:show, Product) %>
            <li><%= link_to t('products.name'), products_path, class: "#{check_active(products_path)}" %></li>
        <% end %>
        <% if can?(:show, Place) %>
            <li><%= link_to t('places.name'), places_path, class: "#{check_active(places_path)}" %></li>
        <% end %>

        <% if can?(:show, Period) %>
            <li><%= link_to t('reports_link'), periods_path, class: "#{check_active(periods_path)}" %></li>
        <% end %>

        <% if can?(:access, :rails_admin) %>
            <li><%= link_to "Admin", '/admin' %></li>
        <% end %>

        <%= login_helper %>

        <% if current_user %>
          <li>
            <%= link_to edit_user_registration_path, class: "#{check_active(edit_user_registration_path)}" do %>
                <%= fa_icon('user') %>
                <%= current_user.name %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <!-- script-for-menu -->
      <script>
        $("span.menu").click(function(){
          $(".top-nav ul").slideToggle("slow" , function(){
          });
        });
      </script>
      <!-- script-for-menu -->
    </div>
    <div class="clearfix"> </div>
  </div>
  <!--//header-->