config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/order-products/:period_id/:user_id', to: 'reports#order_products', as: 'order_products'

  post 'reports/send-order-products/:period_id/:user_id', to: 'reports#send_order_products', as: 'send_products'
  get 'reports/success/:spreadsheet_id', to: 'reports#success', as: 'report_success'
  resources :periods do
    get '/for-cook/:user_id', to: 'orders#for_cook', as: 'for_cook'
    resources :orders
    resources :remainders
    resources :purchases
  end

  resources :places
  resources :products

  resources :dishes do
    resources :ingredients
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :products, through: :ingredients
  has_many :orders

  mount_uploader :image, DishUploader

  validates :name, presence: true, length: {minimum: 5, maximum: 50}, uniqueness: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates :price, presence: true, numericality: true
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  load_and_authorize_resource
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      redirect_to @dish, notice: t('dishes.msg.success.create')
    else
      render :new
    end
  end

  # PATCH/PUT /dishes/1
  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: t('dishes.msg.success.update')
    else
      render :edit
    end
  end

  # DELETE /dishes/1
  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: t('dishes.msg.success.destroy')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.includes(:ingredients).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :description, :price, :image)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper

  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def dish_img(img, type='main')
    if type == 'thumb'
      img.model.image? ? img : image_generator(height: '60', width: '60')
    elsif type == 'middle'
      img.model.image? ? img : image_generator(height: '280', width: '280')
    else
      img.model.image? ? img : image_generator(height: '600', width: '400')
    end
  end
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
      <% dish.errors.full_messages.each do |error| %>
          <%= alert_generator(error) %>
      <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

      <div class="form-group">
        <%= form.label t('dishes.tab.name') %>
        <%= form.text_field :name, id: :dish_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.file_field :image, id: :book_image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label t('dishes.tab.description') %>
        <%= form.text_area :description, id: :dish_description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label t('dishes.tab.price') %>
        <%= form.number_field :price, id: :dish_price, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit t('dishes.save'), class: 'btn btn-primary btn-block' %>
      </div>
  </div>
  <div class="col-md-3"></div>
</div>
<% end %>

app/views/dishes/_item_dishes.html.erb
<div class="col-md-6 w3l-special-grid">
  <div class="col-md-6 w3ls-special-img"
       style="background: url(<%= dish_img(item[0].image.middle, 'middle') %>) no-repeat 0px 0px">
    <div class="wpf-demo-6">
      <div class="w3ls-special-text">
        <p><%= item[0].price %><sub><%= t('currency') %></sub></p>
      </div>
      <figcaption class="view-caption">
        <h4><%= item[0].name %></h4>
        <%= link_to t('button.show'), dish_path(item[0]) %>
      </figcaption>
    </div>
  </div>
  <% if item[1].present? %>
    <div class="col-md-6 w3ls-special-img"
         style="background: url(<%= dish_img(item[1].image.middle, 'middle') %>) no-repeat 0px 0px">
      <div class="wpf-demo-6">
        <div class="w3ls-special-text menu-text">
          <p><%= item[1].price %><sub><%= t('currency') %></sub></p>
        </div>
        <figcaption class="view-caption">
          <h4><%= item[1].name %></h4>
          <%= link_to t('button.show'), dish_path(item[1]) %>
        </figcaption>
      </div>
      <div class="clearfix"> </div>
    </div>
  <% end %>
  <div class="clearfix"> </div>
</div>

app/views/dishes/edit.html.erb
<div class="container">
  <h1><%= t('dishes.view.title_edit') %></h1>
  <%= provide(:title, t('dishes.name')) %>
  <%= render 'form', dish: @dish %>
</div>

<div class="container btn-container">
  <%= render 'shared/link_default', { path: @dish, title: t('button.show') } %>
  <%= render 'shared/link_default', { path: dishes_path, title: t('button.back') } %>
</div>

app/views/dishes/index.html.erb
<%= provide(:title, t('dishes.name')) %>
<div class="menu">
  <div class="container">

    <div class="special-grids menu-grids">
      <% @dishes.in_groups_of(2).each do |item| %>
        <%= render 'item_dishes', item: item %>
      <% end %>
    </div>

  </div>
  <div class="container btn-container">
    <% if can?(:create, Dish)  %>
        <%= render 'shared/link_default', { path: new_dish_path, title: t('dishes.view.title_new') } %>
    <% end %>
  </div>
</div>

app/views/dishes/new.html.erb
<div class="container">
  <h1><%= t('dishes.view.title_new') %></h1>
  <%= provide(:title, t('dishes.name')) %>
  <%= render 'form', dish: @dish %>

  <div class="container btn-container">
    <%= render 'shared/link_default', { path: dishes_path, title: t('button.back') } %>
  </div>
</div>

app/views/dishes/show.html.erb
<%= provide(:title, t('dishes.name')) %>

<div class="blog">
  <div class="container">
    <div class="agile-blog-grids">
      <div class="col-md-8 agile-blog-grid-left">
        <div class="agile-blog-grid">
          <div class="agile-blog-grid-left-img">
            <%= link_to "#" do %>
              <%= image_tag dish_img(@dish.image) %>
            <% end %>
          </div>

        </div>
      </div>
      <div class="col-md-4 agile-blog-grid-right">
        <h3><%= @dish.name %></h3>
        <div class="categories">
          <h3><%= t('ingredient.name') %>:</h3>
          <ul>
            <% @dish.ingredients.each do |ingredient| %>
              <li><b><%= ingredient.product.name_with_unit %> <%= ingredient.quantity %></b></li>
            <% end %>
          </ul>
        </div>
        <div class="categories">
          <p>
            <%= @dish.description %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <h3>
      <% if can?(:create, @dish)  %>
        <%= render 'shared/link_default', { path: edit_dish_path(@dish), title: t('button.edit') } %>
      <% end %>
      <% if can?(:create, Ingredient)  %>
        <%= render 'shared/link_default', { path: dish_ingredients_path(@dish), title: t('button.edit_ingredients') } %>
      <% end %>
      <%= render 'shared/link_default', { path: dishes_path, title: t('button.back') } %>
    </h3>
  </div>
</div>