config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'reports/order-products/:period_id/:user_id', to: 'reports#order_products', as: 'order_products'

  post 'reports/send-order-products/:period_id/:user_id', to: 'reports#send_order_products', as: 'send_products'
  get 'reports/success/:spreadsheet_id', to: 'reports#success', as: 'report_success'
  resources :periods do
    get '/for-cook/:user_id', to: 'orders#for_cook', as: 'for_cook'
    resources :orders
    resources :remainders
    resources :purchases
  end

  resources :places
  resources :products

  resources :dishes do
    resources :ingredients
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: {minimum: 5, maximum: 50}, uniqueness: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates_presence_of :user_id
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  load_and_authorize_resource

  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  def index
    @places = Place.all
  end

  # GET /places/1
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  def create
    @place = Place.new(place_params)

    if @place.save
     redirect_to @place, notice: t('places.success.create')
    else
      render :new
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      redirect_to @place, notice: t('places.success.update')
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    redirect_to places_url, notice: t('places.success.destroy')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :user_id)
    end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <% place.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label  t('places.tab.name') %>
        <%= form.text_field :name, id: :place_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label t('places.tab.description') %>
        <%= form.text_area :description, id: :place_description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label t('places.tab.cook') %>
        <%= form.collection_select(:user_id, User.cooks, :id, :name,
                                   { include_blank: true },
                                   class: 'form-control')
        %>
      </div>

      <div class="actions">
        <%= form.submit t('places.save'), class: 'btn btn-primary btn-block'%>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="container">
  <%= provide(:title, t('places.name')) %>

  <h1><%= t('places.view.title_edit') %></h1>

  <%= render 'form', place: @place %>
</div>

<div class="container btn-container">
  <%= render 'shared/link_default', { path: places_path, title: t('button.back') } %>
  <%= render 'shared/link_default', { path: @place, title: t('button.show') } %>
</div>

app/views/places/index.html.erb
<div class="container empty-container">
  <%= provide(:title, t('places.name')) %>

  <table class="table">
  <thead>
    <tr>
      <th><%= t('places.tab.name') %></th>
      <th><%= t('places.tab.description') %></th>
      <th><%= t('places.tab.cook') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= place.user.name || place.user.email %></td>
        <td>
          <%= link_to edit_place_path(place) do %>
              <i class="fa fa-pencil-square-o"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div class="container btn-container">
  <% if can?(:create, Place) %>
      <%= render 'shared/link_default', { path: new_place_path, title: t('places.view.title_new') } %>
  <% end %>
</div>

app/views/places/new.html.erb
<div class="container">
  <%= provide(:title, t('places.name')) %>

  <h1><%= t('places.view.title_new') %></h1>

  <%= render 'form', place: @place %>
</div>
<div class="container btn-container">
  <%= render 'shared/link_default', { path: places_path, title: t('button.back') } %>
</div>

app/views/places/show.html.erb
<div class="container">
  <%= provide(:title, t('places.name')) %>

  <h2>
    <%= @place.name %>
  </h2>

  <p>
    <strong><%= t('places.tab.description') %>:</strong>
    <%= @place.description %>
  </p>

  <p>
    <strong><%= t('places.tab.cook') %>:</strong>
    <%= @place.user.name %>
  </p>

</div>

<div class="container btn-container">
  <% if can?(:update, @place) %>
      <%= render 'shared/link_default', { path: edit_place_path(@place), title: t('button.edit') } %>
  <% end %>
  <%= render 'shared/link_default', { path: places_path, title: t('button.back') } %>
</div>